#ifndef IDIOMA_PLAYER
#define IDIOMA_PLAYER

#define IDIOMA__ERROR_CARGANDO_EL_IDIOMA							Idioma(0)
#define IDIOMA__ABRIR_ARCHIVO										Sistema.App.Idioma(1)
#define IDIOMA__BASE_DE_DATOS										Sistema.App.Idioma(2)
#define IDIOMA__ECUALIZADOR											Sistema.App.Idioma(3)
#define IDIOMA__VER_VIDEO											Sistema.App.Idioma(4)
#define IDIOMA__LISTA_DE_REPRODUCCION								Sistema.App.Idioma(5)
#define IDIOMA__BUSCAR_ARCHIVOS										Sistema.App.Idioma(6)
#define IDIOMA__OPCIONES											Sistema.App.Idioma(7)
#define IDIOMA__AYUDA												Sistema.App.Idioma(8)
#define IDIOMA__TECLAS_RAPIDAS										Sistema.App.Idioma(9)
#define IDIOMA__ASOCIAR_ARCHIVOS									Idioma(10)
#define IDIOMA__LISTA												Sistema.App.Idioma(11)
#define IDIOMA__ASPECTO												Sistema.App.Idioma(12)
#define IDIOMA__CANCELAR											Sistema.App.Idioma(14)
#define IDIOMA__CANCION_ATRAS										Sistema.App.Idioma(15)
#define IDIOMA__PLAY												Sistema.App.Idioma(16)
#define IDIOMA__PAUSA												Sistema.App.Idioma(17)
#define IDIOMA__STOP												Sistema.App.Idioma(18)
#define IDIOMA__CANCION_ADELANTE									Sistema.App.Idioma(19)
#define IDIOMA__ACTIVADO											Sistema.App.Idioma(20)
#define IDIOMA__DESACTIVADO											Sistema.App.Idioma(21)
#define IDIOMA__SHUFLE												Sistema.App.Idioma(22)
#define IDIOMA__REPEAT												Sistema.App.Idioma(23)
#define IDIOMA__ESTE_REPRODUCTOR_NO									Idioma(24)
#define IDIOMA__LA_RUTA_ESPECIFICADA_NO								Sistema.App.Idioma(25)
#define IDIOMA__ERROR												Sistema.App.Idioma(26)
#define IDIOMA__EDITAR_ANOMALIAS									Sistema.App.Idioma(27)
#define IDIOMA__ASIGNAR_NOMBRE										Sistema.App.Idioma(28)
#define IDIOMA__MODIFICAR_NOMBRE									Sistema.App.Idioma(29)
#define IDIOMA__ELIMINAR											Sistema.App.Idioma(30)
#define IDIOMA__INICIO												Sistema.App.Idioma(31)
#define IDIOMA__REVISAR_MEDIOS										Sistema.App.Idioma(32)
#define IDIOMA__VIDEO												Sistema.App.Idioma(33)
#define IDIOMA__TAMAÑO												Sistema.App.Idioma(34)
#define IDIOMA__REPETIR_LISTA										Sistema.App.Idioma(35)
#define IDIOMA__REPETIR_LISTA_SHUFLE								Sistema.App.Idioma(36)
#define IDIOMA__GENERO_ALEATORIO									Sistema.App.Idioma(37)
#define IDIOMA__GRUPO_ALEATORIO										Sistema.App.Idioma(38)
#define IDIOMA__DISCO_ALEATORIO										Sistema.App.Idioma(39)
#define IDIOMA__50_CANCIONES_ALEATORIAS								Sistema.App.Idioma(40)
#define IDIOMA__APAGAR_WINDOWS										Sistema.App.Idioma(41)
#define IDIOMA__APAGAR_ESTE_REPRODUCTOR								Sistema.App.Idioma(42)
#define IDIOMA__BUSCAR_ARCHIVOS_A_AGREGAR							Sistema.App.Idioma(43)
#define IDIOMA__REVISAR_LA_BASE_DE_DATOS							Sistema.App.Idioma(44)
#define IDIOMA__ARCHIVO												Sistema.App.Idioma(45)
#define IDIOMA__NUEVA_LISTA											Sistema.App.Idioma(46)
#define IDIOMA__LISTA_VACIA											Sistema.App.Idioma(47)
#define IDIOMA__CANCIONES_CON_5_ESTRELLAS							Sistema.App.Idioma(48)
#define IDIOMA__CANCIONES_MAS_ESCUCHADAS							Sistema.App.Idioma(49)
#define IDIOMA__AÑADIR_A_LISTA										Sistema.App.Idioma(50)
#define IDIOMA__GUARDAR_LISTA										Sistema.App.Idioma(51)
#define IDIOMA__CARGAR_ARCHIVO_DE_SUBTITULOS						Sistema.App.Idioma(52)
#define IDIOMA__RESTAURAR											Sistema.App.Idioma(53)
#define IDIOMA__MINIMIZAR											Sistema.App.Idioma(54)
#define IDIOMA__CERRAR												Sistema.App.Idioma(55)
#define IDIOMA__AÑADIR_A_UNA_NUEVA_LISTA							Sistema.App.Idioma(56)
#define IDIOMA__MODIFICAR											Sistema.App.Idioma(57)
#define IDIOMA__NOTA												Sistema.App.Idioma(58)
#define IDIOMA__5_ESTRELLAS											Sistema.App.Idioma(59)
#define IDIOMA__4_ESTRELLAS											Sistema.App.Idioma(60)
#define IDIOMA__3_ESTRELLAS											Sistema.App.Idioma(61)
#define IDIOMA__2_ESTRELLAS											Sistema.App.Idioma(62)
#define IDIOMA__1_ESTRELLA 											Sistema.App.Idioma(63)
#define IDIOMA__ORDEN_DE_LAS_CANCIONES								Sistema.App.Idioma(64)
#define IDIOMA__TIPO_GENERO_GRUPO_DISCO_CANCIONES					Sistema.App.Idioma(65)
#define IDIOMA__GENERO_GRUPO_DISCO_CANCIONES						Sistema.App.Idioma(66)
#define IDIOMA__GRUPO_DISCO_CANCIONES								Sistema.App.Idioma(67)
#define IDIOMA__DISCO_CANCIONES										Sistema.App.Idioma(68)
#define IDIOMA__PROPIEDADES											Sistema.App.Idioma(69)
#define IDIOMA__BUSCAR_CANCION_EN_LA_BASE_DE_DATOS					Sistema.App.Idioma(70)
#define IDIOMA__MODIFICAR_PISTA										Sistema.App.Idioma(71)
#define IDIOMA__TIEMPO												Sistema.App.Idioma(72)
#define IDIOMA__COPIAR_CANCIONES_A									Sistema.App.Idioma(73)
#define IDIOMA__CANCION_ACTUAL										Sistema.App.Idioma(74)
#define IDIOMA__BUSCAR_CANCION_EN_LA_LISTA							Sistema.App.Idioma(75)
#define IDIOMA__ELIMINAR_DE_LA_BASE_DE_DATOS						Sistema.App.Idioma(76)
#define IDIOMA__ELIMINAR_DE_LA_LISTA								Sistema.App.Idioma(77)
#define IDIOMA__ALEATORIO											Sistema.App.Idioma(78)
#define IDIOMA__MODIFICADA											Sistema.App.Idioma(79)
#define IDIOMA__AGREGAR                                             Sistema.App.Idioma(80)
#define IDIOMA__GENERAR												Sistema.App.Idioma(81)
#define IDIOMA__ERROR_CARGANDO_EL_ARCHIVO_S_ESTE_ERROR_NO_ES_GRAVE	Sistema.App.Idioma(82)
#define IDIOMA__ANALIZANDO_											Sistema.App.Idioma(83)
#define IDIOMA__ARCHIVOS_DE_SUBTITULOS_STR							Sistema.App.Idioma(84)
#define IDIOMA__ABRIR_SUBTITULOS									Sistema.App.Idioma(85)
#define IDIOMA__PEQUEÑA												Sistema.App.Idioma(86)
#define IDIOMA__MEDIANA												Sistema.App.Idioma(87)
#define IDIOMA__GRANDE												Sistema.App.Idioma(88)
#define IDIOMA__PISTA												Sistema.App.Idioma(89)
#define IDIOMA__PATH												Sistema.App.Idioma(90)
#define IDIOMA__TIPO												Sistema.App.Idioma(91)
#define IDIOMA__GENERO												Sistema.App.Idioma(92)
#define IDIOMA__GRUPO												Sistema.App.Idioma(93)
#define IDIOMA__DISCO												Sistema.App.Idioma(94)
#define IDIOMA__ESCUCHADA											Sistema.App.Idioma(95)
#define IDIOMA__D_VECES												Sistema.App.Idioma(96)
#define IDIOMA__SIN_DATOS											Sistema.App.Idioma(97)
#define IDIOMA__DATOS_DEL_TAG_VERSION_1								Sistema.App.Idioma(98)
#define IDIOMA__DATOS_DEL_TAG_VERSION_2								Sistema.App.Idioma(99)
#define IDIOMA__DATOS_DEL_TAG_ASF									Sistema.App.Idioma(100)
#define IDIOMA__EL_TOTAL_DE_VALORES_ENCONTRADOS_EN_LOS_TAGS_ES_DE_D Sistema.App.Idioma(101)
#define IDIOMA__GENEROS												Sistema.App.Idioma(102)
#define IDIOMA__GRUPOS												Sistema.App.Idioma(103)
#define IDIOMA__DISCOS												Sistema.App.Idioma(104)
#define IDIOMA__CANCIONES											Sistema.App.Idioma(105)
#define IDIOMA__PRESIONA_LA_NUEVA_TECLA_PARA_ESTA_ACCION			Sistema.App.Idioma(106)
#define IDIOMA__EDITAR												Sistema.App.Idioma(107)
#define IDIOMA__CONTROL_MAS 										Sistema.App.Idioma(108)
#define IDIOMA__ALT_MAS												Sistema.App.Idioma(109)
#define IDIOMA__SHIFT_MAS											Sistema.App.Idioma(110)
#define IDIOMA__COMBINACION_DE_TECLAS_INVALIDA						Sistema.App.Idioma(111)
#define IDIOMA__ACEPTAR												Sistema.App.Idioma(112)
#define IDIOMA__NO_MOSTRAR_MAS_ESTE_MENSAJE							Sistema.App.Idioma(113)
#define IDIOMA__BUSCAR                                              Sistema.App.Idioma(114)
#define IDIOMA__ABRIR_SU_DIRECTORIO									Sistema.App.Idioma(115)
#define IDIOMA__MOSTRAR_LOG											Sistema.App.Idioma(116)
#define IDIOMA__SOBRE_BUBATRONIK									Sistema.App.Idioma(117)
#define IDIOMA__MEDIOS_REPRODUCIBLES								Sistema.App.Idioma(118)
#define IDIOMA__ARCHIVOS_DE_AUDIO									Sistema.App.Idioma(119)
#define IDIOMA__ARCHIVOS_DE_VIDEO									Sistema.App.Idioma(120)
#define IDIOMA__LISTAS												Sistema.App.Idioma(121)
#define IDIOMA__TODOS_LOS_ARCHIVOS									Sistema.App.Idioma(122)
#define IDIOMA__DESEAS_ELIMINAR_TAMBIEN_LOS_MEDIOS_DEL_DISCO_DURO	Sistema.App.Idioma(123)
#define IDIOMA__ELIMINAR_MEDIOS										Sistema.App.Idioma(124)
#define IDIOMA__OMITIR												Sistema.App.Idioma(125)
#define IDIOMA__AYUDA_RAPIDA										Sistema.App.Idioma(126)
#define IDIOMA__AUDIO												Sistema.App.Idioma(127)
#define IDIOMA__CDAUDIO												Sistema.App.Idioma(128)
#define IDIOMA__SELECCIONA_EL_TIPO_DE_NORMA							Sistema.App.Idioma(129)
#define IDIOMA__LISTA_DE_CANCIONES									Sistema.App.Idioma(130)
#define IDIOMA__REVISION_DE_LA_BASE_DE_DATOS						Sistema.App.Idioma(131)
#define IDIOMA___GENERO_GRUPO_DISCO									Sistema.App.Idioma(132)
#define IDIOMA___GRUPO_DISCO										Sistema.App.Idioma(133)
#define IDIOMA___DISCO												Sistema.App.Idioma(134)
#define IDIOMA__MEDIO_SIGUIENTE										Sistema.App.Idioma(135)
#define IDIOMA__MEDIO_ANTERIOR										Sistema.App.Idioma(136)
#define IDIOMA__GRUPO_DESCONOCIDO									Sistema.App.Idioma(137)
#define IDIOMA__DISCO_DESCONOCIDO									Sistema.App.Idioma(138)
#define IDIOMA__CD_DE_AUDIO_S										Sistema.App.Idioma(139)
#define IDIOMA__GENERO_SELECCIONADO_S								Sistema.App.Idioma(140)
#define IDIOMA___MODIFICADA_										Sistema.App.Idioma(141)
#define IDIOMA__GENERO_ALEATORIO_S									Sistema.App.Idioma(142)
#define IDIOMA__GENERO_SUGERIDO_S									Sistema.App.Idioma(143)
#define IDIOMA__GRUPO_ALEATORIO_S									Sistema.App.Idioma(144)
#define IDIOMA__GRUPO_SUGERIDO_S									Sistema.App.Idioma(145)
#define IDIOMA__DISCO_ALEATORIO_S									Sistema.App.Idioma(146)
#define IDIOMA__DISCO_SUGERIDO_S									Sistema.App.Idioma(147)
#define IDIOMA__D_CANCIONES_ALEATORIAS								Sistema.App.Idioma(148)
#define IDIOMA___CANCIONES_CON_5_ESTRELLAS_							Sistema.App.Idioma(149)
#define IDIOMA___LAS_D_CANCIONES_MAS_ESCUCHADAS_					Sistema.App.Idioma(150)
#define IDIOMA__GENERO_MAS_ESCUCHADO_S								Sistema.App.Idioma(151)
#define IDIOMA__GRUPO_MAS_ESCUCHADO_S								Sistema.App.Idioma(152)
#define IDIOMA__DISCO_MAS_ESCUCHADO_S								Sistema.App.Idioma(153)
#define IDIOMA__ERROR_GRAVE											Sistema.App.Idioma(154)
#define IDIOMA__ENVIAR												Sistema.App.Idioma(155)
#define IDIOMA__TERMINAR											Sistema.App.Idioma(156)
#define IDIOMA__LA_OPERACION_SE_HA_COMPLETADO_CORRECTAMENTE			Sistema.App.Idioma(157)
#define IDIOMA__LISTA_M3U_M3U										Sistema.App.Idioma(158)
//#define IDIOMA__GUARDAR_LISTA										Sistema.App.Idioma(159)
#define IDIOMA__EL_ARCHIVO_S_YA_EXISTE								Sistema.App.Idioma(160)
#define IDIOMA__YA_EXISTE_UN_ARCHIVO								Sistema.App.Idioma(161)
#define IDIOMA__NO_SE_HA_PODIDO_GUARDAR_EL_ARCHIVO					Sistema.App.Idioma(162)
#define IDIOMA__ERROR_GUARDANDO_LA_LISTA							Sistema.App.Idioma(163)
#define IDIOMA__LA_LISTA_SE_HA_GUARDADO_EN_S						Sistema.App.Idioma(164)
#define IDIOMA__LISTA_GUARDADA										Sistema.App.Idioma(165)
#define IDIOMA__CURSOR_ADELANTE										Sistema.App.Idioma(166)
#define IDIOMA__CURSOR_ATRAS										Sistema.App.Idioma(167)
#define IDIOMA__CURSOR_IZQUIERDA									Sistema.App.Idioma(168)
#define IDIOMA__CURSOR_DERECHA										Sistema.App.Idioma(169)
#define IDIOMA__ESPACIO												Sistema.App.Idioma(170)
#define IDIOMA__RETROCESO											Sistema.App.Idioma(171)
#define IDIOMA__INSERT												Sistema.App.Idioma(172)
#define IDIOMA__SUPRIMIR											Sistema.App.Idioma(173)
//#define IDIOMA__INICIO												Sistema.App.Idioma(174)
#define IDIOMA__FIN													Sistema.App.Idioma(175)
#define IDIOMA__ESC													Sistema.App.Idioma(176)
#define IDIOMA__SHIFT												Sistema.App.Idioma(177)
#define IDIOMA__IMPRIMIR_PANTALLA									Sistema.App.Idioma(178)
#define IDIOMA__ARCHIVO_DE_AUDIO									Sistema.App.Idioma(179)
#define IDIOMA__ARCHIVO_DE_VIDEO									Sistema.App.Idioma(180)
#define IDIOMA__NUMERACION											Sistema.App.Idioma(181)
#define IDIOMA__ANCHO												Sistema.App.Idioma(182)
#define IDIOMA__ALTO												Sistema.App.Idioma(183)
#define IDIOMA__DATOS_DEL_TAG_VORBIS								Sistema.App.Idioma(184)

// ESCENAS
// ControlPresentacionEx::Mostrar_Inicio
#define IDIOMA__BIENVENIDO_A_S_S																										Sistema.App.Idioma(1000)
#define IDIOMA__LISTA_ACTUAL_S																											Sistema.App.Idioma(1001)
#define IDIOMA__NO_HAY_SUGERENCIAS_BD																									Sistema.App.Idioma(1002)
#define IDIOMA__NUMERO_DE_CANCIONES_LISTA																								Sistema.App.Idioma(1003)
#define IDIOMA__D_GENEROS_D_GRUPOS																										Sistema.App.Idioma(1004)
#define IDIOMA__EL_GENERO_MAS_ESCUCHADO_ES																								Sistema.App.Idioma(1005)
#define IDIOMA__EL_GRUPO_MAS_ESCUCHADO_ES																								Sistema.App.Idioma(1006)
#define IDIOMA__EL_DISCO_MAS_ESCUCHADO_ES																								Sistema.App.Idioma(1007)
#define IDIOMA__SUGERENCIAS_S_S																											Sistema.App.Idioma(1008)
#define IDIOMA__SIN_SUGERENCIAS																											Sistema.App.Idioma(1009)
#define IDIOMA__GENERADOR_DE_LISTAS																										Sistema.App.Idioma(1010)
#define IDIOMA__LISTA_CON_50_CANCIONES_BASADAS_EN_UN_GENERO																				Sistema.App.Idioma(1011)
#define IDIOMA__LISTA_CON_50_CANCIONES_BASADAS_EN_UN_GRUPO																				Sistema.App.Idioma(1012)
#define IDIOMA__LISTA_CON_50_CANCIONES_BASADAS_EN_UN_DISCO																				Sistema.App.Idioma(1013)
#define IDIOMA__LISTA_CON_50_CANCIONES_ALEATORIAS																						Sistema.App.Idioma(1014)
#define IDIOMA__LISTA_CON_5ESTRELLAS																									Sistema.App.Idioma(1015)
#define IDIOMA__LISTA_CON_MAS_ESCUCHADAS																								Sistema.App.Idioma(1016)
#define IDIOMA__MEDIOS_ABIERTOS_RECIENTEMENTE																							Sistema.App.Idioma(1017)
// ControlPresentacionEx::Mostrar_CargandoVLC
#define IDIOMA__CARGANDO_NUCLEO_DE_LA_LIBVLC_S																							Sistema.App.Idioma(1020)
// ControlPresentacionEx::Mostrar_SobreBubaTronik
#define IDIOMA__BUBATRONIK_ES_UNA_APLICACION_QUE_NACIO_ANTE_LA_NECESIDAD_DE_ORDENAR_Y_REPRODUCIR_MEDIOS_FACILMENTE						Sistema.App.Idioma(1030)
#define IDIOMA__BUBATRONIK_LA_DWL_Y_WWW_DEVILDREY33_ES_SON_PROPIEDAD_DE_JOSE_ANTONIO_BOVER_COMAS										Sistema.App.Idioma(1031)
#define IDIOMA__SI_DESEAIS_PONEROS_EN_CONTACTO_CON_EL_AUTOR_PODEIS_HACERLO_ENVIANDO_UN_MENSAJE_EN_EL_FORO_DE_WWW_DEVILDREY33_ES			Sistema.App.Idioma(1032)
#define IDIOMA__HAY_MUCHA_GENTE_QUE_HA_COLABORADO_ACTIVA_Y_PASIVAMENTE_EN_ESTE_PROYECTO_COSA_QUE_DEBO_AGRADECER							Sistema.App.Idioma(1033)
#define IDIOMA__BARBA_SIEMPRE_DA_BUENAS_OPINIONES_PARA_PROBLEMAS_POCO_COMUNES															Sistema.App.Idioma(1034)
#define IDIOMA__FONG_APORTACION_DE_VARIAS_IDEAS_Y_UNA_VALIOSA_COBAYA																	Sistema.App.Idioma(1035)
#define IDIOMA__MICHEL_APORTACION_DE_VARIAS_IDEAS_Y_UNA_VALIOSA_COBAYA																	Sistema.App.Idioma(1036)
#define IDIOMA__PARRIS_OTRA_VALIOSA_COBAYA																								Sistema.App.Idioma(1037)
#define IDIOMA__TXEMA_OTRA_VALIOSA_COBAYA																								Sistema.App.Idioma(1038)
#define IDIOMA__TAMBIEN_TENGO_QUE_AGRADECER_A_TODA_LA_GENTE_QUE_ME_HA_DADO_APOYO_Y_SOPORTE_DURANTE_ESTE_PROYECTO_GRACIAS_A_TODOS		Sistema.App.Idioma(1039)
#define IDIOMA__POR_ULTIMO_TAMBIEN_DEBO_MENCIONAR_QUE_ESTE_REPRODUCTOR_UTILIZA_OTRAS_2_LIBRERIAS_PARA_CUMPLIR_SU_COMETIDO_Y_SON			Sistema.App.Idioma(1040)
#define IDIOMA__FMOD_EX_426_POTENTE_LIBRERIA_DE_AUDIO_UTILIZADA_EN_MUCHOS_JUEGOS_ACTUALES												Sistema.App.Idioma(1041)
#define IDIOMA__PUEDES_ENCONTRARLA_EN_EL_SIGUIENTE_ENLACE_HTTP_WWW_FMOD_ORG																Sistema.App.Idioma(1042)
#define IDIOMA__LIBVLC_S_LIBRERIA_PARA_REPRODUCIR_PRACTICAMENTE_CUALQUIER_MEDIO															Sistema.App.Idioma(1043)
#define IDIOMA__PUEDES_ENCONTRARLA_EN_EL_SIGUIENTE_ENLACE_HTTP_WWW_VIDEOLAN_ORG															Sistema.App.Idioma(1044)
#define IDIOMA__DATOS_ADICIONALES																										Sistema.App.Idioma(1045)
#define IDIOMA__BUBATRONIK_F_S_COMPILADO_CON_MSVC_D_EL_S																				Sistema.App.Idioma(1046)
#define IDIOMA__VERSION_DE_WINDOWS_D_D_SERVICE_PACK_D_D																					Sistema.App.Idioma(1047)
// ControlPresentacionEx::Mostrar_Opciones_Lista
#define IDIOMA__LISTA_INICIAL																											Sistema.App.Idioma(1050)
#define IDIOMA__ELIGE_QUE_DEBE_HACER_EL_REPRODUCTOR_SI_SE_INICIA_CON_UNA_LISTA_VACIA													Sistema.App.Idioma(1051)
#define IDIOMA__NOTA_SI_ELIGES_LA_OPCION_CUALQUIER_COSA_EL_REPRODUCTOR_SELECCIONARA_UNA_DE_LAS_OPCIONES_DE_LA_LISTA_ALEATORIAMENTE		Sistema.App.Idioma(1052)
#define IDIOMA__CUALQUIER_COSA																											Sistema.App.Idioma(1053)		
#define IDIOMA__EXCLUIR_CANCIONES																										Sistema.App.Idioma(1054)
#define IDIOMA__ESTA_OPCION_TE_PERMITE_EXCLUIR_LAS_CANCIONES_QUE_TENGAN_UNA_ESTRELLA_DE_TODAS_LAS_LISTAS_ALEATORIAS						Sistema.App.Idioma(1055)
#define IDIOMA__EXCLUIR_CANCIONES_CON_UNA_ESTRELLA																						Sistema.App.Idioma(1056)
// ControlPresentacionEx::Mostrar_Opciones_BD
#define IDIOMA__MOSTRAR_TAGS																											Sistema.App.Idioma(1060)
#define IDIOMA__SI_ACTIVAS_ESTA_OPCION_EN_LOS_TOOLTIPS_INFORMATIVOS_SE_MOSTRARAN_TODOS_LOS_DATOS_DEL_TAG								Sistema.App.Idioma(1061)
#define IDIOMA__MOSTRAR_TAGS_EN_LOS_TOOLTIPS																							Sistema.App.Idioma(1062)
// ControlPresentacionEx::Mostrar_Opciones_Video
#define IDIOMA__OPCIONES_DE_VIDEO																										Sistema.App.Idioma(1070)
#define IDIOMA__ESTA_OPCION_OCULTARA_EL_MOUSE_CUANDO_EL_REPRODUCTOR_ESTE_EN_MODO_PANTALLA_COMPLETA										Sistema.App.Idioma(1071)
#define IDIOMA__OCULTAR_MOUSE_EN_PANTALLA_COMPLETA																						Sistema.App.Idioma(1072)
// ControlPresentacionEx::Mostrar_Opciones_Apariencia
#define IDIOMA__TAMANO_DE_LA_FUENTE																										Sistema.App.Idioma(1080)
#define IDIOMA__SELECCIONA_EL_TAMANO_DE_LA_FUENTE_QUE_USARA_EL_REPRODUCTOR																Sistema.App.Idioma(1081)
#define IDIOMA__CONFIGURACION_DE_COLORES																								Sistema.App.Idioma(1082)
#define IDIOMA__ELIGE_LA_CONFIGURACION_DE_COLORES_QUE_PREFIERAS_PARA_EL_REPRODUCTOR														Sistema.App.Idioma(1083)
#define IDIOMA__NOTA_PUEDES_CREAR_EDITAR_UNA_CONFIGURACION_DE_COLORES_EDITANDO_LOS_ARCHIVOS_CON_EXTENSION								Sistema.App.Idioma(1084)
#define IDIOMA__TAMANO_DEL_ESPECTRO_GRAFICO																								Sistema.App.Idioma(1085)
#define IDIOMA__SELECCIONA_EL_TAMANO_DE_LAS_BARRAS_PARA_EL_ESPECTRO_GRAFICO_DEL_SONIDO													Sistema.App.Idioma(1086)
#define IDIOMA__BARRA_DE_TITULO																											Sistema.App.Idioma(1087)
#define IDIOMA__UTILIZAR_BARRA_DE_TITULO_DE_WINDOWS_RECOMENDADO_EN_WINDOWS_VISTA_Y_SUPERIORES											Sistema.App.Idioma(1088)
#define IDIOMA__UTILIZAR_BARRA_DE_TITULO_DE_WINDOWS																						Sistema.App.Idioma(1089)
// -ControlPresentacionEx::Mostrar_Opciones
#define IDIOMA__IDIOMA																													Sistema.App.Idioma(1090)
#define IDIOMA__ELIGE_QUE_IDIOMA_PREFIERES_QUE_SE_MUESTRE_EN_EL_REPRODUCTOR																Sistema.App.Idioma(1091)
#define IDIOMA__ACTUALIZACIONES																											Sistema.App.Idioma(1092)
#define IDIOMA__BUSCAR_EN_INTERNET_UNA_NUEVA_VERSION_DEL_REPRODUCTOR_AL_INICIAR															Sistema.App.Idioma(1093)
#define IDIOMA__BUSCAR_ACTUALIZACIONES																									Sistema.App.Idioma(1094)
#define IDIOMA__REPRODUCTOR_SIEMPRE_DELANTE																								Sistema.App.Idioma(1095)
#define IDIOMA__ESTA_OPCION_TE_PERMITE_TENER_POR_DELANTE_DE_TODAS_LAS_OTRAS_VENTANAS_LA_VENTANA_DEL_REPRODUCTOR							Sistema.App.Idioma(1096)
#define IDIOMA__TIPOS_DE_ARCHIVO																										Sistema.App.Idioma(1097)
#define IDIOMA__LOS_TIPOS_DE_ARCHIVO_QUE_SE_VEN_A_CONTINUACION_SON_LOS_TIPOS_QUE_USARA_EL_REPRODUCTOR									Sistema.App.Idioma(1098)
#define IDIOMA__ELIMINAR_AUDIO																											Sistema.App.Idioma(1099)
#define IDIOMA__ELIMINAR_VIDEO																											Sistema.App.Idioma(1100)
#define IDIOMA__ELIMINAR_SELECCIONADOS																									Sistema.App.Idioma(1101)
#define IDIOMA__RESTAURAR_TIPOS																											Sistema.App.Idioma(1102)
#define IDIOMA__ASOCIAR_TIPOS																											Sistema.App.Idioma(1103)
#define IDIOMA__ESTA_OPCION_TE_PERMITE_ASOCIAR_LOS_TIPOS_DE_ARCHIVO_DE_LA_LISTA_ANTERIOR_AL_REPRODUCTOR									Sistema.App.Idioma(1104)
#define IDIOMA__PREGUNTAR_AL_INICIAR_CUANDO_SEA_NECESARIO																				Sistema.App.Idioma(1105)
#define IDIOMA__SIEMPRE_																												Sistema.App.Idioma(1106)
#define IDIOMA__NUNCA_																													Sistema.App.Idioma(1107)
#define IDIOMA__SELECCIONA_COMO_QUIERES_QUE_SE_EJECUTEN_LOS_ARCHIVOS_POR_DEFECTO														Sistema.App.Idioma(1108)
#define IDIOMA__ANADIR_A_LISTA																											Sistema.App.Idioma(1109)
#define IDIOMA__REPRODUCIR																												Sistema.App.Idioma(1110)
// -ControlPresentacionEx::Mostrar_Opciones_Teclado
#define IDIOMA__TECLAS_DE_ACCESO_RAPIDO																									Sistema.App.Idioma(1120)	
#define IDIOMA__PUEDES_CAMBIAR_LAS_TECLAS_PARA_CUALQUIER_ACCION_DE_LAS_QUE_SE_LISTAN_A_CONTINUACION										Sistema.App.Idioma(1121)
#define IDIOMA__PLAY_PAUSA																												Sistema.App.Idioma(1122)
#define IDIOMA__SUBIR_VOLUMEN																											Sistema.App.Idioma(1123)
#define IDIOMA__BAJAR_VOLUMEN																											Sistema.App.Idioma(1124)
#define IDIOMA__REPRODUCIR_MEDIO_SIGUIENTE																								Sistema.App.Idioma(1125)
#define IDIOMA__REPRODUCIR_MEDIO_ANTERIOR																								Sistema.App.Idioma(1126)
#define IDIOMA__OBTENER_TECLADO_FUERA_DE_LA_APLICACION																					Sistema.App.Idioma(1127)
#define IDIOMA__MARCA_ESTA_OPCION_PARA_QUE_EL_REPRODUCTOR_DETECTE_LAS_TECLAS_DE_ACCESO_RAPIDO_INCLUSO_BAJO_UN_JUEGO						Sistema.App.Idioma(1128)
#define IDIOMA__OBTENER_TECLADO_CUANDO_EL_REPRODUCTOR_NO_ESTE_ACTIVO																	Sistema.App.Idioma(1129)
// RESERVAMOS 10 ESPACIOS PARA MOSTRAR_OPCIONES_TECLADO QUE PROBABLEMENTE SERA MODIFICADA EN UN FUTURO
// -ControlPresentacionEx::Mostrar_RevisarBD 
#define IDIOMA__DESDE_ESTE_PANEL_PUEDES_REVISAR_LA_BASE_DE_DATOS_PARA_DETERMINAR_SI_SE_HAN_BORRADO_CANCIONES_DE_LOS_DISCOS				Sistema.App.Idioma(1140)
#define IDIOMA__ES_IMPORTANTE_QUE_REVISES_LA_BASE_DE_DATOS_CUANDO_BORRES_CANCIONES_DESDE_FUERA_DEL_REPRODUCTOR							Sistema.App.Idioma(1141)
#define IDIOMA__POR_ULTIMO_TAMBIEN_PUEDES_HACER_UNA_REVISION_PARA_DETERMINAR_QUE_GENEROS_GRUPOS_DISCOS_SE_PARECEN_ENTRE_SI				Sistema.App.Idioma(1142)
#define IDIOMA__REVISAR_ANOMALIAS_EN_GENEROS_GRUPOS_DISCOS																				Sistema.App.Idioma(1143)
// -ControlPresentacionEx::Mostrar_BuscarArchivos
#define IDIOMA__EL_REPRODCUTOR_BUSCARA_NUEVOS_MEDIOS_REPRODUCIBLES_EN_LOS_DIRECTORIOS_QUE_SE_MUESTRAN_EN_LA_LISTA_DE_ABAJO				Sistema.App.Idioma(1150)
#define IDIOMA___PATH_																													Sistema.App.Idioma(1151)
#define IDIOMA___TAG_																													Sistema.App.Idioma(1152)
#define IDIOMA__PATH_GENERO_GRUPO_DISCO																									Sistema.App.Idioma(1153)
#define IDIOMA__PATH_GRUPO_DISCO																										Sistema.App.Idioma(1154)
#define IDIOMA__PATH_DISCO																												Sistema.App.Idioma(1155)
#define IDIOMA__INDEFINIDO																												Sistema.App.Idioma(1156)
#define IDIOMA__SELECCIONA_UN_DIRECTORIO																								Sistema.App.Idioma(1157)
#define IDIOMA__SUGERENCIAS																												Sistema.App.Idioma(1158)
#define IDIOMA__SELECCIONA_QUE_TIPO_DE_NORMA_DEBERIAS_UTILIZAR_PARA_LA_ESTRUCTURACCION_DEL_DIRECTORIO_QUE_HAS_ELEGIDO					Sistema.App.Idioma(1159)
#define IDIOMA__1_GENERO_GRUPO_DISCO_ESCANEO_POR_PATH																					Sistema.App.Idioma(1160)
#define IDIOMA__2_GRUPO_DISCO_ESCANEO_POR_PATH																							Sistema.App.Idioma(1161)
#define IDIOMA__3_DISCO_ESCANEO_POR_TAG																									Sistema.App.Idioma(1162)
#define IDIOMA__4_UN_POCO_DE_TODO_INDEFINIDO_ESCANEO_POR_TAG																			Sistema.App.Idioma(1163)
#define IDIOMA__PATH_ANTES_DEL_TAG																										Sistema.App.Idioma(1164)
#define IDIOMA__TAG_ANTES_DEL_PATH																										Sistema.App.Idioma(1165)
#define IDIOMA__ESTE_PROCESO_PUEDE_TARDAR_VARIOS_MINUTOS_DEPENDIENDO_DEL_ORDENADOR_Y_EL_NUMERO_DE_ARCHIVOS_REPRODUCIBLES				Sistema.App.Idioma(1166)
#define IDIOMA__FILTRADO_DE_CARACTERES																									Sistema.App.Idioma(1167)
#define IDIOMA__ANALISIS_POST_ESCANEO																									Sistema.App.Idioma(1168)




// Mensajes
#define IDIOMA__ERROR_LA_UNIDAD_QUE_CONTIENE_EL_MEDIO_NO_SE_ENCUENTRA_DISPONIBLE_POR_ELLO_ES_IMPOSIBLE_REPRODUCIR_EL_MEDIO				Sistema.App.Idioma(4000)
#define IDIOMA__REVISION_TERMINADA_SE_HAN_ELIMINADO_UN_TOTA_DE_D_ENTRADAS_NO_VALIDAS													Sistema.App.Idioma(4001)
#define IDIOMA__ERROR_LA_RUTA_INTRODUCIDA_NO_ES_VALIDA_O_YA_EXISTE_EN_LA_LISTA															Sistema.App.Idioma(4002)
#define IDIOMA__DESEAS_ELIMINAR_EL_M3U_DEL_DISCO_ESTO_NO_AFECTARA_A_LOS_MEDIOS_QUE_CONTIENE_EL_M3U										Sistema.App.Idioma(4003)
#define IDIOMA__BUBATRONIK_HA_ENCONTRADO_UN_ERROR_CRITICO_Y_ADEMAS_NO_HA_PODIDO_CREAR_UN_INFORME_DE_ERRORES								Sistema.App.Idioma(4004)
#define IDIOMA__LA_VERSION_DE_LA_BASE_DE_DATOS_NO_ES_VALIDA_PARA_ESTE_REPRODUCTOR														Sistema.App.Idioma(4005)
#define IDIOMA__LA_BASE_DE_DATOS_PARECE_ESTAR_DANADA																					Sistema.App.Idioma(4006)
#define IDIOMA__HAY_D_MEDIOS_QUE_NO_SE_HAN_CARGADO_DEBIDO_A_QUE_SU_INFORMACION_PODRIA_SER_INVALIDA										Sistema.App.Idioma(4007)
#define IDIOMA__IGNORADA_CARGA_DE_ALGUNOS_MEDIOS																						Sistema.App.Idioma(4008)
#define IDIOMA__HA_SUCEDIDO_UN_ERROR_GRAVE_EN_BUBATRONIK_Y_ESTE_DEBE_CERRARSE															Sistema.App.Idioma(4009)
#define IDIOMA__SE_HA_CREADO_UN_INFORME_DE_ERRORES_DESEAS_ENVIARLO_A_WWW_DEVILDREY33_ES													Sistema.App.Idioma(4010)
#define IDIOMA__PULSA_EL_BOTON_ENVIAR_PARA_ENVIAR_EL_MENSAJE_Y_TERMINAR_O_PULSA_EL_BOTON												Sistema.App.Idioma(4011)
#define IDIOMA__TERMINAR_PARA_QUE_NO_SE_MANDE_EL_MENSAJE																				Sistema.App.Idioma(4012)
#define IDIOMA__INFORMACION																												Sistema.App.Idioma(4013)
#define IDIOMA__INFORME_DE_ERRORES_ENVIADO_CORRECTAMENTE																				Sistema.App.Idioma(4014)
#define IDIOMA__ERROR_ENVIANDO_EL_INFORME_DE_ERRORES																					Sistema.App.Idioma(4015)
#define IDIOMA__SE_HA_ENCONTRADO_UNA_NUEVA_ACTUALIZACION_DE_BUBATRONIK_DESEAS_DESCARGARLA												Sistema.App.Idioma(4016)
#define IDIOMA__NUEVA_ACTUALIZACION																										Sistema.App.Idioma(4017)
#define IDIOMA__EL_REPRODUCTOR_SE_APAGARA_PARA_ACTUALIZARSE																				Sistema.App.Idioma(4018)
#define IDIOMA__ACTUALIZAR																												Sistema.App.Idioma(4019)
#define IDIOMA__ERROR_DESCARGANDO_LA_ACTUALIZACION																						Sistema.App.Idioma(4020)
#define IDIOMA__EMPEZANDO_ACTUALIZACION																									Sistema.App.Idioma(4021)
#define IDIOMA__ERROR_DE_DESCARGA																										Sistema.App.Idioma(4022)
#define IDIOMA__ERROR_CARGANDO_WINSOCK																									Sistema.App.Idioma(4023)
#define IDIOMA__ERROR_OBTENIENDO_LA_IP																									Sistema.App.Idioma(4024)
#define IDIOMA__ERROR_SOCKET_INVALIDO																									Sistema.App.Idioma(4025)
#define IDIOMA__ERROR_CONECTANDO_AL_SERVIDOR																							Sistema.App.Idioma(4026)
#define IDIOMA__ERROR_DURANTE_LA_TRANSMISION																							Sistema.App.Idioma(4027)
#define IDIOMA__ERROR_LA_VERSION_DEL_SKIN_NO_ES_VALIDA_PARA_ESTE_REPRODUCTOR															Sistema.App.Idioma(4028)
#define IDIOMA__ERROR_CARGANDO_ARCHIVO_DE_SKIN_S																						Sistema.App.Idioma(4029)
#define IDIOMA__NO_PUEDES_ANADIR_MEDIOS_EXTERNAMENTE_MIENTRAS_SE_ESTA_REALIZANDO_UNA_BUSQUEDA											Sistema.App.Idioma(4030)


// ToolTips
// -ID_GENERAR_LISTA
#define IDIOMA__DEBES_ELEGIR_UN_TIPO_DE_LISTA_PARA_PODER_GENERARLA																		Sistema.App.Idioma(5000)
#define IDIOMA__AL_PRESIONAR_ESTE_BOTON_CREARAS_UNA_NUEVA_LISTA																			Sistema.App.Idioma(5001)
#define IDIOMA__DE_UNAS_50_CANCIONES_DEL_TIPO_ELEGIDO																					Sistema.App.Idioma(5002)
// -ID_TIPOS_LISTA
#define IDIOMA__ESTE_CONTROL_TE_PERMITE_ELEGIR_ENTRE_VARIOS_TIPOS_DE_LISTAS_PREFABRICADAS												Sistema.App.Idioma(5010)
#define IDIOMA__LISTA_DE_CANCIONES_ALEATORIAS_BASADAS_EN_GENERO																			Sistema.App.Idioma(5011)
#define IDIOMA__LISTA_DE_CANCIONES_ALEATORIAS_BASADAS_EN_GRUPO																			Sistema.App.Idioma(5012)
#define IDIOMA__LISTA_DE_CANCIONES_ALEATORIAS_BASADAS_EN_DISCO																			Sistema.App.Idioma(5013)
#define IDIOMA__LISTA_DE_CANCIONES_ALEATORIAS_SIN_BASARSE_EN_NADA																		Sistema.App.Idioma(5014)
#define IDIOMA__LISTA_CON_LAS_CANCIONES_MAS_ESCUCHADAS_SI_SE_HA_ESCUCHADO_ALGUNA														Sistema.App.Idioma(5015)
#define IDIOMA__LISTA_CON_CANCIONES_DE_5_ESTRELLAS_SI_SE_HA_ASIGNADO_ALGUNA																Sistema.App.Idioma(5016)
#define IDIOMA__NOTA_ESTAS_LISTAS_COMO_MAXIMO_PODRAN_TENER_50_CANCIONES																	Sistema.App.Idioma(5017)
// -CP_SUGERENCIA_GENERO1 -CP_SUGERENCIA_GENERO2 -CP_SUGERENCIA_GRUPO1 -CP_SUGERENCIA_GRUPO2 -CP_SUGERENCIA_DISCO1 -CP_SUGERENCIA_DISCO2
#define IDIOMA__CADA_VEZ_QUE_ACCEDAS_A_LA_SECCION_DE_INICIO_SE_MOSTRARAN_NUEVAS_SUGERENCIAS												Sistema.App.Idioma(5020)
// -CP_SUGERENCIA_GENERO1 -CP_SUGERENCIA_GENERO2 -CP_GENERO_MAS
#define IDIOMA__HAZ_CLICK_PARA_CREAR_UNA_NUEVA_LISTA_CON_VARIAS_CANCIONES_DEL_GENERO													Sistema.App.Idioma(5021)
// -CP_SUGERENCIA_GRUPO1 -CP_SUGERENCIA_GRUPO2 -CP_GRUPO_MAS
#define IDIOMA__HAZ_CLICK_PARA_CREAR_UNA_NUEVA_LISTA_CON_VARIAS_CANCIONES_DEL_GRUPO														Sistema.App.Idioma(5022)
// -CP_SUGERENCIA_DISCO1 -CP_SUGERENCIA_DISCO2 -CP_DISCO_MAS
#define IDIOMA__HAZ_CLICK_PARA_CREAR_UNA_NUEVA_LISTA_CON_VARIAS_CANCIONES_DEL_DISCO														Sistema.App.Idioma(5023)
// -CP_GENERO_MAS
#define IDIOMA__PARA_DETERMINAR_QUE_GENERO_SE_HA_ESCUCHADO_SE_HACE_UNA_LISTA_CON_TODOS_LOS_GENEROS										Sistema.App.Idioma(5024)
#define IDIOMA__EN_LA_QUE_SE_SUMAN_LAS_VECES_QUE_SE_HA_ESCUCHADO_CADA_CANCION_DE_ESE_GENERO												Sistema.App.Idioma(5025)
// -CP_GRUPO_MAS			
#define IDIOMA__PARA_DETERMINAR_QUE_GRUPO_SE_HA_ESCUCHADO_SE_HACE_UNA_LISTA_CON_TODOS_LOS_GRUPOS										Sistema.App.Idioma(5026)
#define IDIOMA__EN_LA_QUE_SE_SUMAN_LAS_VECES_QUE_SE_HA_ESCUCHADO_CADA_CANCION_DE_ESE_GRUPO												Sistema.App.Idioma(5027)
// -CP_DISCO_MAS
#define IDIOMA__PARA_DETERMINAR_QUE_DISCO_SE_HA_ESCUCHADO_SE_HACE_UNA_LISTA_CON_TODOS_LOS_DISCOS										Sistema.App.Idioma(5028)
#define IDIOMA__EN_LA_QUE_SE_SUMAN_LAS_VECES_QUE_SE_HA_ESCUCHADO_CADA_CANCION_DE_ESE_DISCO												Sistema.App.Idioma(5029)
// -ID_FILTRO_COINCIDENCIAS
#define IDIOMA__ACTIVANDO_ESTA_OPCION_EL_REPRODUCTOR_REALIZARA_UNA_COMPROBACION_ENTRE_TODOS_SUS_GENEROS_GRUPOS_Y_DISCOS					Sistema.App.Idioma(5030)
#define IDIOMA__DE_FORMA_QUE_SOLUCIONE_EL_80_DE_ERRATAS_EN_LOS_TAGS																		Sistema.App.Idioma(5031)
#define IDIOMA__PONGAMOS_POR_EJEMPLO_QUE_INICIALMENTE_SE_ENCUENTRAN_LOS_SIGUIENTES_DOS_GRUPOS											Sistema.App.Idioma(5032)
#define IDIOMA__IRONMAIDEN_Y_IRON_MAIDEN																								Sistema.App.Idioma(5033)
#define IDIOMA__SI_OS_FIJAIS_SON_PRACTICAMENTE_LO_MISMO_PERO_UNO_TIENE_UN_ESPACIO_EN_MEDIO_Y_EL_OTRO_NO									Sistema.App.Idioma(5034)
#define IDIOMA__UNA_COSA_TAN_SIMPLE_COMO_ESTA_HACE_QUE_EL_REPRODUCTOR_INTERPRETE_ESOS_RESULTADOS_COMO_2_GRUPOS_DISTINTOS				Sistema.App.Idioma(5035)
#define IDIOMA__Y_POR_ESO_SE_HA_CREADO_ESTA_OPCION_PARA_INTENTAR_CORREGIR_AL_MAXIMO_ESTE_TIPO_DE_ERRORES								Sistema.App.Idioma(5036)
#define IDIOMA__NOTA_																													Sistema.App.Idioma(5037)
#define IDIOMA__ACTIVANDO_ESTA_OPCION_EL_TIEMPO_TOTAL_DE_LA_BUSQUEDA_DE_ARCHIVOS_SE_INCREMENTA_NOTABLEMENTE								Sistema.App.Idioma(5038)
// -ID_FILTRO_CARACTERES
#define IDIOMA__ACTIVANDO_ESTA_OPCION_EL_REPRODUCTOR_FILTRARA_DE_TODOS_LOS_NOMBRES_LOS_SIGUIENTES_CARACTERES							Sistema.App.Idioma(5040)
#define IDIOMA__CARACTERESRAROS_ADEMAS_DE_LAS_TILDES_Y_SIMBOLOS_DE_PUNTUACION															Sistema.App.Idioma(5041)
#define IDIOMA__CON_ESTO_CONSEGUIMOS_MUCHA_MAS_PRECISION_A_LA_HORA_DE_IDENTIFICAR_GENEROS_GRUPOS_Y_DISCOS								Sistema.App.Idioma(5042)
#define IDIOMA__ES_MUY_RECOMENDABLE_DEJAR_ACTIVADA_ESTA_OPCION_ADEMAS_DE_QUE_NO_AFECTARA_EL_TIEMPO_DE_LA_BUSQUEDA						Sistema.App.Idioma(5043)
// -ID_BOTON_BUSCAR2
#define IDIOMA__PRESIONA_ESTE_BOTON_PARA_EMPEZAR_LA_BUSQUEDA																			Sistema.App.Idioma(5050)
#define IDIOMA__ANTES_DE_HACERLO_DEBERIAS_ASEGURARTE_DE_QUE_HAS_ANADIDO_LAS_RUTAS_QUE_DESEAS_BUSCAR_EN_LA_LISTA							Sistema.App.Idioma(5051)
#define IDIOMA__PRESIONA_ESTE_BOTON_PARA_CANCELAR_LA_BUSQUEDA																			Sistema.App.Idioma(5052)
#define IDIOMA__PARA_BUSCAR_PRIMERO_TIENES_QUE_AGREGAR_UNA_RUTA_A_LA_LISTA_Y_ELEGIR_EL_TIPO_DE_ORDEN									Sistema.App.Idioma(5053)
// -ID_BOTON_AGREGAR_DIR
#define IDIOMA__AL_PULSAR_ESTE_BOTON_ANADIRAS_EL_DIRECTORIO_DEL_CUADRO_DESPLEGABLE_A_LA_LISTA_DE_DIRECTORIOS							Sistema.App.Idioma(5060)
#define IDIOMA__NO_ES_RECOMENDABLE_ANADIR_LA_RAIZ_DE_NINGUN_DISCO_DURO_EXCEPTUANDO_EL_CASO_DE_QUE_ESE_DISCO								Sistema.App.Idioma(5061)
#define IDIOMA__SEA_UNICAMENTE_PARA_MEDIOS_DE_AUDIO_Y_VIDEO																				Sistema.App.Idioma(5062)
// -ID_COMBO_DIR
#define IDIOMA__DESDE_ESTE_CONTROL_DESPLEGABLE_PUEDES_BUSCAR_DIRECTORIOS_PARA_ANADIR_A_LA_LISTA											Sistema.App.Idioma(5070)
#define IDIOMA__LOS_DIRECTORIOS_DE_LA_LISTA_DE_ARRIBA_SON_LOS_QUE_ESCANEARA_EL_REPRODUCTOR_PARA_ENCONTRAR_NUEVOS_MEDIOS					Sistema.App.Idioma(5071)
// -ID_DIRECTORIOS_BUSCAR
#define IDIOMA__ESTA_LISTA_CONTIENE_LOS_DIRECTORIOS_EN_LOS_QUE_EL_REPRODUCTOR_BUSCARA_NUEVOS_MEDIOS_REPRODUCIBLES						Sistema.App.Idioma(5080)
#define IDIOMA__POR_DEFECTO_SE_HAN_ANADIDO_LAS_RUTAS_PREDETERMINADAS_DE_WINDOWS_SI_DESEAS_ELIMINARLAR_PUEDES_USAR						Sistema.App.Idioma(5081)
#define IDIOMA__EL_BOTON_CON_UNA_CRUZ_ROJA_SITUADO_EN_LA_PARTE_INFERIOR_DERECHA_DE_ESTA_LISTA											Sistema.App.Idioma(5082)
#define IDIOMA__SI_QUIERES_AGREGAR_DIRECTORIOS_DEBES_UTILIZAR_EL_CONTROL_DESPLEGABLE_QUE_HAY_MAS_ABAJO_PARA_SELECCIONAR					Sistema.App.Idioma(5083)
#define IDIOMA__EL_DIRECTORIO_QUE_QUIERAS_Y_POR_ULTIMO_DEBES_PRESIONAR_EL_BOTON_AGREGAR_PARA_INSERTARLO_EN_ESTA_LISTA					Sistema.App.Idioma(5084)
// -ID_LISTA_IDIOMAS
#define IDIOMA__ESTA_LISTA_CONTIENE_LOS_IDIOMAS_DISPONIBLES_PARA_ESTE_REPRODUCTOR														Sistema.App.Idioma(5090)
#define IDIOMA__SI_ESTAS_INTERESADO_EN_AGREGAR_UN_NUEVO_IDIOMA_A_ESTA_APLICACION_PONTE_EN_CONTACTO_CON_DEVILDREY33						Sistema.App.Idioma(5091)
#define IDIOMA__A_TRAVES_DEL_FORO_DE_HTTP_WWW_DEVILDREY33_ES																			Sistema.App.Idioma(5092)
// -ID_BUSCAR_ACTUALIZACIONES
#define IDIOMA__ACTIVANDO_ESTA_OPCION_EL_REPRODUCTOR_SE_CONECTARA_UNA_VEZ_AL_DIA_COMO_MAXIMO_PARA_COMPROBAR_SI_EXISTEN					Sistema.App.Idioma(5100)
#define IDIOMA__NUEVAS_ACTUALIZACIONES_POR_INSTALAR																						Sistema.App.Idioma(5101)
// -ID_SIEMPRE_DELANTE
#define IDIOMA__ACTIVANDO_ESTA_OPCION_EL_REPRODUCTOR_SE_QUEDARA_SIEMPRE_DELANTE_DE_LAS_OTRAS_VENTANAS									Sistema.App.Idioma(5110)
// -ID_LISTA_TIPOS
#define IDIOMA__ESTA_LISTA_CONTIENE_TODOS_LOS_TIPOS_DE_AUDIO_Y_DE_VIDEO_QUE_EL_REPRODUCTOR_ACEPTA_POR_DEFECTO							Sistema.App.Idioma(5120)
#define IDIOMA__PUEDES_ELIMINAR_AQUELLAS_ESTENSIONES_QUE_NO_TE_INTERESE_QUE_EL_REPRODUCTOR_ACEPTE										Sistema.App.Idioma(5121)
// -ID_BOTON_ELIMINAR_TIPOS_AUDIO
#define IDIOMA__ESTE_BOTON_ELIMINARA_DE_LA_LISTA_TODOS_LOS_TIPOS_QUE_SEAN_PREDEFINIDOS_PARA_AUDIO										Sistema.App.Idioma(5130)
// -ID_BOTON_ELIMINAR_TIPOS_VIDEO
#define IDIOMA__ESTE_BOTON_ELIMINARA_DE_LA_LISTA_TODOS_LOS_TIPOS_QUE_SEAN_PREDEFINIDOS_PARA_VIDEO										Sistema.App.Idioma(5140)
// -ID_BOTON_ELIMINAR_TIPOS
#define IDIOMA__ESTE_BOTON_ELIMINARA_DE_LA_LISTA_TODOS_LOS_TIPOS_QUE_SE_ENCUENTREN_SELECCIONADOS_EN_ESTE_MOMENTO						Sistema.App.Idioma(5150)
// -ID_BOTON_RESTAURAR_TIPOS
#define IDIOMA__ESTE_BOTON_RESTAURARA_TODOS_LOS_TIPOS_QUE_PUEDE_USAR_BUBATRONIK_POR_DEFECTO												Sistema.App.Idioma(5160)
// -ID_ASOCIAR_PREGUNTAR
#define IDIOMA__SELECCIONADO_ESTA_OPCION_EL_REPRODUCTOR_MIRARA_CADA_VEZ_QUE_SE_INICIE_SI_ESTA_ASOCIADO_A_LOS							Sistema.App.Idioma(5170)
#define IDIOMA__TIPOS_DE_LA_LISTA_EN_CASO_DE_NO_ESTAR_ASOCIADO_A_ALGUNO_DE_ESOS_TIPOS_EL_REPRODUCTOR_MOSTRARA							Sistema.App.Idioma(5171)
#define IDIOMA__UN_MENSAJE_QUE_TE_PEDIRA_SI_DESEAS_ASOCIAR_EL_REPRODUCTOR_A_LOS_TIPOS_DE_LA_LISTA										Sistema.App.Idioma(5172)
// -ID_ASOCIAR_SIEMPRE (el 5170 es lo mismo que seria el 5180)
#define IDIOMA__TIPOS_DE_LA_LISTA_EN_CASO_DE_NO_ESTAR_ASOCIADO_A_ALGUNO_DE_ESOS_TIPOS_EL_REPRODUCTOR_SE_ASOCIARA						Sistema.App.Idioma(5181)
#define IDIOMA__A_ELLOS_AUTOMATICAMENTE_SIN_PREGUNTAR_NADA																				Sistema.App.Idioma(5182)
// -ID_ASOCIAR_NUNCA			
#define IDIOMA__SELECCIONANDO_ESTA_OPCION_EL_REPRODUCTOR_OMITIRA_ESCANEAR_EL_REGISTRO_PARA_DETERMINAR_SI_ESTA							Sistema.App.Idioma(5190)
#define IDIOMA__ASOCIADO_O_NO_A_LOS_TIPOS_DE_ARCHIVO_DE_LA_LISTA																		Sistema.App.Idioma(5191)
// -ID_ASOCIAR_ADD
#define IDIOMA__AL_EJECUTAR_UN_ARCHIVO_ASOCIADO_AL_REPRODUCTOR_DESDE_EL_EXPLORADOR_SE_ANADIRA_A_LA_LISTA_SIN							Sistema.App.Idioma(5200)
#define IDIOMA__INTERRUMPIR_LA_REPRODUCCION_ACTUAL																						Sistema.App.Idioma(5201)
// -ID_ASOCIAR_REP
#define IDIOMA__AL_EJECUTAR_UN_ARCHIVO_ASOCIADO_AL_REPRODUCTOR_DESDE_EL_EXPLORADOR_SE_ANADIRA_A_LA_LISTA								Sistema.App.Idioma(5210)
#define IDIOMA__INTERRUMPIENDO_LA_REPRODUCCION_ACTUAL_Y_SE_PONDRA_A_REPRODUCIR_EL_PRIMER_MEDIO_ANADIDO_DESDE							Sistema.App.Idioma(5211)
#define IDIOMA__EL_EXPLORADOR																											Sistema.App.Idioma(5212)
// -ID_OPCIONES_FUENTE			
#define IDIOMA__EN_ESTA_LISTA_PUEDES_SELECCIONAR_EL_TAMANO_DE_LA_FUENTE_QUE_MAS_SE_AJUSTE_A_TUS_NECESIDADES								Sistema.App.Idioma(5220)
#define IDIOMA__HAY_TRES_TIPOS_DE_TAMANO_PEQUENO_11PX_MEDIANO_13PX_Y_GRANDE_15_PX														Sistema.App.Idioma(5221)
// -ID_OPCIONES_SKIN
#define IDIOMA__EN_ESTA_LISTA_PUEDES_SELECCIONAR_LA_CONFIGURACION_DE_COLORES_QUE_MAS_TE_GUSTE											Sistema.App.Idioma(5230)
#define IDIOMA__SI_DESEAS_CREAR_UNA_CONFIGURACION_DE_COLORES_PARA_BUBATRONIK_Y_NO_LO_VES_MUY_CLARO										Sistema.App.Idioma(5231)
#define IDIOMA__PUEDES_CONSULTAR_TUS_DUDAS_EN_EL_FORO_DE_HTTP_WWW_DEVILDREY33_ES														Sistema.App.Idioma(5232)
// -ID_OPCIONES_OSCY
#define IDIOMA__EN_ESTA_LISTA_PUEDES_SELECCIONAR_EL_TAMANO_DE_LAS_BARRITAS_DEL_ESPECTRO_GRAFICO											Sistema.App.Idioma(5240)
#define IDIOMA__EL_PEQUENO_HACE_1_PIXEL_DE_ANCHO_EL_MEDIANO_2_PIXELES_Y_EL_GRANDE_3_PIXELES												Sistema.App.Idioma(5241)
// -ID_OPCIONES_UTILIZAR_BARRA_WIN
#define IDIOMA__MARCANDO_ESTA_OPCION_EL_REPRODUCTOR_UTILIZARA_LA_BARRA_DE_WINDOWS_ESTANDAR_CON_SUS_BORDES								Sistema.App.Idioma(5250)
#define IDIOMA__EN_PRINCIPIO_EL_REPRODUCTOR_SE_DISEÑO_PARA_WINDOWS_XP_POR_LO_QUE_SE_CREO_UNA_BARRA_DE_TITULO							Sistema.App.Idioma(5251)
#define IDIOMA__DISTINTA_A_LA_DE_WINDOWS_QUE_QUEDABA_MAS_ACORDE_CON_EL_REPRODUCTOR														Sistema.App.Idioma(5252)
#define IDIOMA__SI_ESTAS_USANDO_WINDOWS_VISTA_O_WINDOWS_7_SE_RECOMIENDA_UTILIZAR_LA_BARRA_DE_TITULO_DE_WINDOWS							Sistema.App.Idioma(5253)
#define IDIOMA__PARA_NO_PERDER_LAS_CAPACIDADES_EXTENDIDAS_DE_MAXIMIZADO_PARCIAL															Sistema.App.Idioma(5254)
// -ID_OPCIONES_MOSTRAR_TAG			
#define IDIOMA__MARCANDO_ESTA_OPCION_SE_CARGARAN_AL_VUELO_Y_SE_MOSTRARAN_LOS_TAG_DE_LAS_CANCIONES_AL_MOSTRAR							Sistema.App.Idioma(5260)
#define IDIOMA__EL_TOOLTIP_INFORMATIVO																									Sistema.App.Idioma(5261)
#define IDIOMA__CON_EL_CUARTO_BOTON_DEL_MOUSE_PUEDES_HACER_APARECER_ESOS_TOOLTIPS_DENTRO_DE_LA_LISTA_Y_DE_LA							Sistema.App.Idioma(5262)
#define IDIOMA__BASE_DE_DATOS_SIN_TENER_QUE_ESPERAR_2_SEGUNDOS_ENCIMA_DE_LA_CANCION														Sistema.App.Idioma(5263)
// -ID_LISTA_INICIO 
#define IDIOMA__EN_ESTA_LISTA_DESPLEGABLE_PUEDES_SELECCIONAR_QUE_QUIERES_QUE_HAGA_EL_REPRODUCTOR_AL_INICIARSE							Sistema.App.Idioma(5270)
#define IDIOMA__CREAR_UNA_LISTA_PARTIENDO_DE_UN_GENERO_ALEATORIO_CON_UN_MAXIMO_DE_50_CANCIONES											Sistema.App.Idioma(5271)
#define IDIOMA__CREAR_UNA_LISTA_PARTIENDO_DE_UN_GRUPO_ALEATORIO_CON_UN_MAXIMO_DE_50_CANCIONES											Sistema.App.Idioma(5272)
#define IDIOMA__CREAR_UNA_LISTA_PARTIENDO_DE_UN_DISCO_ALEATORIO_CON_UN_MAXIMO_DE_50_CANCIONES											Sistema.App.Idioma(5273)
#define IDIOMA__CREAR_UNA_LISTA_ALEATORIA_CON_UN_MAXIMO_DE_50_CANCIONES																	Sistema.App.Idioma(5274)
#define IDIOMA__CUALQUIER_COSA_UNA_DE_LAS_4_OPCIONES_ANTERIORES_ALEATORIAMENTE															Sistema.App.Idioma(5275)
#define IDIOMA__CREAR_UNA_LISTA_VACIA																									Sistema.App.Idioma(5276)
#define IDIOMA__SI_EL_REPRODUCTOR_SE_INICIA_DESDE_EL_EXPLORADOR_PORQUE_HAS_ABIERTO_UN_MEDIO_DESDE_ALLI_LA_CREACION						Sistema.App.Idioma(5277)
#define IDIOMA__DE_LA_LISTA_ALEATORIA_SE_OMITIRA																						Sistema.App.Idioma(5278)
// -ID_EXCLUIR_NOTA 
#define IDIOMA__MARCANDO_ESTA_OPCION_EL_REPRODUCTOR_EVITARA_CREAR_LISTAS_ALEATORIAS_CON_CANCIONES_QUE_SOLO_TENGAN_UNA_ESTRELLA			Sistema.App.Idioma(5280)
#define IDIOMA__EL_SISTEMA_DE_NOTAS_PARA_LOS_MEDIOS_POR_DEFECTO_LE_DA_2_ESTRELLAS_A_TODOS_LOS_MEDIOS_SI_DESEAS_QUE_UN_MEDIO				Sistema.App.Idioma(5281)
#define IDIOMA__TENGA_MAS_NOTA_HASTA_5_ESTRELLAS_PUEDES_CAMBIARLE_LA_NOTA_UTILIZANDO_EL_MENU_DESPLEGABLE_DESDE_LA_LISTA_O_LA			Sistema.App.Idioma(5282)
#define IDIOMA__BASE_DE_DATOS_																											Sistema.App.Idioma(5283)
// -ID_OPCIONES_TECLA_PLAY 
#define IDIOMA__DESDE_ESTE_CONTROL_PUEDES_SELECCIONAR_LA_TECLA_QUE_SE_USARA_PARA_REALIZAR_LA_ACCION_PLAY_PAUSA							Sistema.App.Idioma(5290)
// -ID_OPCIONES_TECLA_STOP
#define IDIOMA__DESDE_ESTE_CONTROL_PUEDES_SELECCIONAR_LA_TECLA_QUE_SE_USARA_PARA_REALIZAR_LA_ACCION_STOP								Sistema.App.Idioma(5300)
// -ID_OPCIONES_TECLA_VOLUMEN_MAS 
#define IDIOMA__DESDE_ESTE_CONTROL_PUEDES_SELECCIONAR_LA_TECLA_QUE_SE_USARA_PARA_REALIZAR_LA_ACCION_SUBIR_EL_VOLUMEN					Sistema.App.Idioma(5310)
// -ID_OPCIONES_TECLA_VOLUMEN_MENOS 
#define IDIOMA__DESDE_ESTE_CONTROL_PUEDES_SELECCIONAR_LA_TECLA_QUE_SE_USARA_PARA_REALIZAR_LA_ACCION_BAJAR_EL_VOLUMEN					Sistema.App.Idioma(5320)
// -ID_OPCIONES_TECLA_SIGUIENTE
#define IDIOMA__DESDE_ESTE_CONTROL_PUEDES_SELECCIONAR_LA_TECLA_QUE_SE_USARA_PARA_REALIZAR_LA_ACCION_SIGUIENTE_MEDIO						Sistema.App.Idioma(5330)
// -ID_OPCIONES_TECLA_ANTERIOR 
#define IDIOMA__DESDE_ESTE_CONTROL_PUEDES_SELECCIONAR_LA_TECLA_QUE_SE_USARA_PARA_REALIZAR_LA_ACCION_ANTERIOR_MEDIO						Sistema.App.Idioma(5340)
// -ID_OPCIONES_OCULTAR_MOUSE 
#define IDIOMA__MARCANDO_ESTA_OPCION_EN_EL_MODO_DE_PANTALLA_COMPLETA_DENTRO_DE_UN_VIDEO_EL_MOUSE_SE_OCULTARA							Sistema.App.Idioma(5350)
#define IDIOMA__PASADOS_2_SEGUNDOS_SIN_HACER_NADA_ESTO_OCURRIRA_SIEMPRE_QUE_EL_MOUSE_NO_ESTE_EN_LA_PARTE_DE_LOS_CONTROLES				Sistema.App.Idioma(5351)
// -CP_URL_FMOD 
#define IDIOMA__PAGINA_WEB_DE_ESTA_FABULOSA_LIBRERIA_PARA_AUDIO																			Sistema.App.Idioma(5360)
// -CP_URL_LIBVLC 
#define IDIOMA__PAGINA_WEB_DE_ESTA_EXCELENTE_LIBRERIA_PARA_AUDIO_VIDEO																	Sistema.App.Idioma(5370)
// -CP_URL_DEVILDREY33 
#define IDIOMA__PAGINA_WEB_DE_DEVILDREY33																								Sistema.App.Idioma(5380)
// -CP_URL_MALEIT 
#define IDIOMA__PAGINA_WEB_DEL_GRUPO_DE_ESTE_CRACK_A_LA_BATERIA_MALEIT																	Sistema.App.Idioma(5390)
// -CP_URL_BUBATRONIK 
#define IDIOMA__PAGINA_WEB_PRINCIPAL_DE_ESTE_REPRODUCTOR																				Sistema.App.Idioma(5400)
// -CP_URL_DWL 
#define IDIOMA__PAGINA_WEB_DE_LA_DREY_WINDOWS_LIB																						Sistema.App.Idioma(5410)
#define IDIOMA__LA_DWL_ES_UNA_LIBRERIA_PARA_HACER_APLICACIONES_BAJO_WINDOWS_EN_C														Sistema.App.Idioma(5411)
#define IDIOMA__QUE_SE_DISTRIBUYE_BAJO_LICENCIA_GPL																						Sistema.App.Idioma(5412)
// -CP_URL_FORO 
#define IDIOMA__FORO_DE_HTTP_WWW_DEVILDREY33_ES																							Sistema.App.Idioma(5420)
// -ID_COMBO_ORDEN_DIR
#define IDIOMA__ESTAS_NORMAS_SE_USAN_A_LA_HORA_DE_OBTENER_LOS_DATOS_DE_UN_MEDIO_PARA_DETERMINAR_MEJOR_SUS_DATOS							Sistema.App.Idioma(5430)
#define IDIOMA__SI_POR_EJEMPLO_TENEMOS_EL_DIRECTORIO_C_MP3_Y_DENTRO_TENEMOS_MUSICA_ESTRUCTURADA_SEGUN_GRUPO_DISCO_PODEMOS				Sistema.App.Idioma(5431)
#define IDIOMA__ENCONTRAR_EL_CASO_EN_QUE_ADEMAS_EXISTA_UN_DIRECTORIO_PARA_DISTINTOS_CDS_EJEMPLO											Sistema.App.Idioma(5432)
#define IDIOMA__C_MP3_BARON_ROJO_BARON_AL_ROJO_VIVO_CD1																					Sistema.App.Idioma(5433)
#define IDIOMA__EN_ESTE_CASO_CONCRETO_SI_ESTAMOS_BUSCANDO_DATOS_BASANDONOS_EN_EL_PATH_Y_NO_SE_HA_ELEGIDO_EL_TIPO_GRUPO_DISCO			Sistema.App.Idioma(5434)
#define IDIOMA__EL_REPRODUCTOR_PENSARA_QUE_EL_NOMBRE_DEL_GRUPO_ES_BARON_AL_ROJO_VIVO_Y_EL_DISCO_CD1_COSA_QUE_ES_INCORRECTA				Sistema.App.Idioma(5435)
#define IDIOMA__PRIMERO_DEBES_SELECCIONAR_UN_DIRECTORIO_ANTES_DE_PODER_ESTABLECER_EL_TIPO_DE_NORMA_A_UTILIZAR							Sistema.App.Idioma(5436)
// -ID_MARCA_PATH
#define IDIOMA__MARCANDO_ESTA_OPCION_EL_REPRODUCTOR_DARA_PRIORIDAD_A_LOS_DATOS_DEL_PATH_POR_ENCIMA_DE_LOS_DEL_TAG_PARA_EL_DIRECTORIO_QUE_SE_VA_A_AGREGAR		Sistema.App.Idioma(5440)
#define IDIOMA__PRIMERO_DEBES_SELECCIONAR_UN_DIRECTORIO_ANTES_DE_PODER_ESTABLECER_LA_PRIORIDAD_DE_LOS_DATOS								Sistema.App.Idioma(5441)
// -ID_MARCA_TAG
#define IDIOMA__MARCANDO_ESTA_OPCION_EL_REPRODUCTOR_DARA_PRIORIDAD_A_LOS_DATOS_DEL_TAG_POR_ENCIMA_DE_LOS_DEL_PATH_PARA_EL_DIRECTORIO_QUE_SE_VA_A_AGREGAR		Sistema.App.Idioma(5442)

#endif